spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: frankocosic
    password: frankocosic
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080