spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/usertable
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework: DEBUG

server:
  port: 8080
