spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usertable
    username: user
    password: user
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080